language: python
python:
- '3.6'
- '3.7'
dist: bionic
#services:
#- docker
#- mysql
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y wget
- pip install codecov
- pip install pytest-cov
- pip install codacy-coverage
- git clone https://github.com/volodymyrss/nbworkflow-test.git tests/testrepo
install:
- pip install -r requirements.txt
- pip install pysqlite3>=3.8.3 --upgrade
- pip install -r tests/testrepo/requirements.txt
- pip install .
script:
- PYTHONPATH=./ TEST_NOTEBOOK=$PWD/tests/testrepo/workflow-notebook.ipynb TEST_NOTEBOOK_REPO=$PWD/tests/testrepo/ py.test . --cov=./ --maxfail=1
after_success:
- coverage xml
- python-codacy-coverage -r coverage.xml
- codecov
